-- This contains some default data for the database.

BEGIN;

-- Default data values should be added during the transaction.

INSERT INTO countries (country) VALUES ('Afghanistan');
INSERT INTO countries (country) VALUES ('Algeria');
INSERT INTO countries (country) VALUES ('Algeria-Niger');
INSERT INTO countries (country) VALUES ('Antarctica');
INSERT INTO countries (country) VALUES ('Argentina');
INSERT INTO countries (country) VALUES ('Armenia');
INSERT INTO countries (country) VALUES ('Armenia-Azerbaijan');
INSERT INTO countries (country) VALUES ('Australia');
INSERT INTO countries (country) VALUES ('Bolivia');
INSERT INTO countries (country) VALUES ('Brazil');
INSERT INTO countries (country) VALUES ('Burma (Myanmar)');
INSERT INTO countries (country) VALUES ('Cameroon');
INSERT INTO countries (country) VALUES ('Canada');
INSERT INTO countries (country) VALUES ('Cape Verde');
INSERT INTO countries (country) VALUES ('Chad');
INSERT INTO countries (country) VALUES ('Chile');
INSERT INTO countries (country) VALUES ('Chile-Argentina');
INSERT INTO countries (country) VALUES ('Chile-Bolivia');
INSERT INTO countries (country) VALUES ('Chile-Peru');
INSERT INTO countries (country) VALUES ('China');
INSERT INTO countries (country) VALUES ('China-North Korea');
INSERT INTO countries (country) VALUES ('Colombia');
INSERT INTO countries (country) VALUES ('Colombia-Ecuador');
INSERT INTO countries (country) VALUES ('Comoros');
INSERT INTO countries (country) VALUES ('Costa Rica');
INSERT INTO countries (country) VALUES ('Djibouti');
INSERT INTO countries (country) VALUES ('Dominica');
INSERT INTO countries (country) VALUES ('DR Congo');
INSERT INTO countries (country) VALUES ('DR Congo-Rwanda');
INSERT INTO countries (country) VALUES ('Ecuador');
INSERT INTO countries (country) VALUES ('El Salvador');
INSERT INTO countries (country) VALUES ('El Salvador-Guatemala');
INSERT INTO countries (country) VALUES ('Equatorial Guinea');
INSERT INTO countries (country) VALUES ('Eritrea');
INSERT INTO countries (country) VALUES ('Eritrea-Djibouti');
INSERT INTO countries (country) VALUES ('Ethiopia');
INSERT INTO countries (country) VALUES ('Ethiopia-Djibouti');
INSERT INTO countries (country) VALUES ('Ethiopia-Eritrea');
INSERT INTO countries (country) VALUES ('Ethiopia-Eritrea-Djibouti');
INSERT INTO countries (country) VALUES ('Ethiopia-Kenya');
INSERT INTO countries (country) VALUES ('Fiji');
INSERT INTO countries (country) VALUES ('France');
INSERT INTO countries (country) VALUES ('Georgia');
INSERT INTO countries (country) VALUES ('Germany');
INSERT INTO countries (country) VALUES ('Greece');
INSERT INTO countries (country) VALUES ('Grenada');
INSERT INTO countries (country) VALUES ('Guatemala');
INSERT INTO countries (country) VALUES ('Guatemala-El Salvador');
INSERT INTO countries (country) VALUES ('Honduras');
INSERT INTO countries (country) VALUES ('Iceland');
INSERT INTO countries (country) VALUES ('India');
INSERT INTO countries (country) VALUES ('Indonesia');
INSERT INTO countries (country) VALUES ('Iran');
INSERT INTO countries (country) VALUES ('Iran-Azerbaijan');
INSERT INTO countries (country) VALUES ('Italy');
INSERT INTO countries (country) VALUES ('Japan');
INSERT INTO countries (country) VALUES ('Japan - administered by Russia');
INSERT INTO countries (country) VALUES ('Kenya');
INSERT INTO countries (country) VALUES ('Libya');
INSERT INTO countries (country) VALUES ('Madagascar');
INSERT INTO countries (country) VALUES ('Malaysia');
INSERT INTO countries (country) VALUES ('Mali');
INSERT INTO countries (country) VALUES ('Mexico');
INSERT INTO countries (country) VALUES ('Mexico-Guatemala');
INSERT INTO countries (country) VALUES ('Mongolia');
INSERT INTO countries (country) VALUES ('Netherlands');
INSERT INTO countries (country) VALUES ('New Zealand');
INSERT INTO countries (country) VALUES ('Nicaragua');
INSERT INTO countries (country) VALUES ('Niger');
INSERT INTO countries (country) VALUES ('Nigeria');
INSERT INTO countries (country) VALUES ('North Korea');
INSERT INTO countries (country) VALUES ('North Korea-South Korea');
INSERT INTO countries (country) VALUES ('Norway');
INSERT INTO countries (country) VALUES ('Pakistan');
INSERT INTO countries (country) VALUES ('Panama');
INSERT INTO countries (country) VALUES ('Papua New Guinea');
INSERT INTO countries (country) VALUES ('Peru');
INSERT INTO countries (country) VALUES ('Philippines');
INSERT INTO countries (country) VALUES ('Portugal');
INSERT INTO countries (country) VALUES ('Russia');
INSERT INTO countries (country) VALUES ('Saint Kitts and Nevis');
INSERT INTO countries (country) VALUES ('Saint Lucia');
INSERT INTO countries (country) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO countries (country) VALUES ('Samoa');
INSERT INTO countries (country) VALUES ('Sao Tome and Principe');
INSERT INTO countries (country) VALUES ('Saudi Arabia');
INSERT INTO countries (country) VALUES ('Solomon Islands');
INSERT INTO countries (country) VALUES ('South Africa');
INSERT INTO countries (country) VALUES ('South Korea');
INSERT INTO countries (country) VALUES ('Spain');
INSERT INTO countries (country) VALUES ('Sudan');
INSERT INTO countries (country) VALUES ('Syria');
INSERT INTO countries (country) VALUES ('Taiwan');
INSERT INTO countries (country) VALUES ('Tanzania');
INSERT INTO countries (country) VALUES ('Tonga');
INSERT INTO countries (country) VALUES ('Turkey');
INSERT INTO countries (country) VALUES ('Uganda');
INSERT INTO countries (country) VALUES ('Uganda-Rwanda');
INSERT INTO countries (country) VALUES ('Undersea Features');
INSERT INTO countries (country) VALUES ('United Kingdom');
INSERT INTO countries (country) VALUES ('United States');
INSERT INTO countries (country) VALUES ('Vanuatu');
INSERT INTO countries (country) VALUES ('Vietnam');
INSERT INTO countries (country) VALUES ('Yemen');


COMMIT;